sudo: false

language: php

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=3.7.11 DEPLOY_BRANCH=master
    - php: 5.6
      env: WP_VERSION=3.7.11
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest BUILD=git
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=latest

before_script: ./ci/prepare.sh

script: ./ci/test.sh

after_success: ./ci/deploy.sh

cache:
  directories:
  - vendor

branches:
  only:
    - master
    - release-0-23-1

notifications:
  email:
    on_success: never
    on_failure: change
