sudo: false
dist: trusty

language: php
php: 7.1

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - ./ci/prepare.sh

jobs:
  include:
    - stage: sniff
      script: composer lint && composer phpcs
      env: BUILD=sniff
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 7.2
      env: WP_VERSION=latest
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 7.1
      env: WP_VERSION=latest
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 7.0
      env: WP_VERSION=latest
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 5.6
      env: WP_VERSION=latest
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 5.6
      env: WP_VERSION=trunk
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 5.6
      env: WP_VERSION=latest BUILD=git WP_CLI_BIN_DIR=''
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 5.6
      env: WP_VERSION=3.7.11
    - stage: test
      script: composer prepare-tests && composer phpunit && composer behat
      php: 5.4
      dist: precise
      env: WP_VERSION=3.7.11

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^release-.+$/

notifications:
  email:
    on_success: never
    on_failure: change
