language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.4.2 WP_MULTISITE=0
    - WP_VERSION=3.4.2 WP_MULTISITE=1

before_script:
    # install dependencies
    - composer install --dev --no-interaction --prefer-source
    # set up WP install
    - WP_CORE_DIR=/tmp/wp-cli-test-core-download-cache/
    - mkdir -p $WP_CORE_DIR
    - wget -nv -O /tmp/wordpress.tar.gz http://wordpress.org/wordpress-$WP_VERSION.tar.gz
    - tar --strip-components=1 -zxmf /tmp/wordpress.tar.gz -C $WP_CORE_DIR
    # set up database
    - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
    - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot

script: vendor/bin/phpunit && vendor/bin/behat
